spring:
  datasource:
    # 💡 여기에 &allowPublicKeyRetrieval=true 를 추가했습니다!
    url: jdbc:mysql://localhost:3306/dukdangdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
gemini:
  api-key: #본인의 키
  # 깃허브에 올릴 때 삭제
  model: gemini-2.5-flash

jwt:
  secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY=
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

file:
  upload-dir: uploads/images
  upload-url: http://localhost:8080/uploads/images