spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dukdangdb?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY=
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html